### ISSUE TITLE
Markdown comments in the template break config parsing

### ISSUE THREAD

**Issue by jcgruenhage** [rustic-games/jilu#19]
Markdown comments inside the template break the parsing of the config inside the changelog. The fix to this is counting opening/closing comment markers and only reading the config *after* the outermost opening comment marker has been closed (or rather, the outermost closing comment marker has been opened, considering the CHANGELOG is read in reverse order.

**Comment by jcgruenhage** [comment]
(The problem described in #15 is caused by this most likely btw)

**Comment by JeanMertz** [comment]
Thanks for the detailed report. I'm tracking this in #14. I'll close this one, and hopefully have a fix ready sometime tomorrow.
